CI: Retry multi-GPU tests on flake (#828)
## Describe your changes

There's a known flake #826 in our multi-GPU tests. The issue has an active huggingface GH issue, so we can wait and see whether HF fixes the issue for us. In the meantime, this PR makes the multi-GPU tests retry if we see the flake. 

CircleCI has no built-in mechanism for retrying failed steps, so we need to write our own logic for it.
> Note: CircleCI does not support automatic retries of failed steps, jobs & workflows. If you are looking for that feature, please vote for it [here](https://ideas.circleci.com/cloud-feature-requests/p/support-automatic-retry-of-failed-builds).

source: https://support.circleci.com/hc/en-us/articles/360043188514-How-to-Retry-a-Failed-Step-with-when-Attribute

## Issue ticket number and link

## Describe tests performed


## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have considered how it would affect the multi-GPU case and tested on a multi-GPU node if appropriate.
- [ ] If it is a high-risk change, I have run the following experiments to verify that the results are as expected:
    - [ ] [experiment=ian/027_eval_refactored_random_token_imdb model.name_or_path=AlignmentResearch/robust_llm_pythia-imdb-1.4b-mz-ada-v3](https://wandb.ai/farai/robust-llm/runs/zlynwimq)
    - [ ] [experiment=ian/028_eval_refactored_gcg_imdb model.name_or_path=AlignmentResearch/robust_llm_pythia-imdb-2.8b-mz-ada-v3](https://wandb.ai/farai/robust-llm/runs/pi6eq0wp)
    - [ ] [experiment=niki/1_DEBUG_niki_128](https://wandb.ai/farai/robust-llm/runs/76h9beb3)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -188,16 +188,49 @@ jobs:
           name: Run multigpu tests
           command: |
             mkdir -p /tmp/test-reports
-            # --exitfirst: Although we'd prefer to see all test results,
-            # sometimes only one process will fail a test (without printing any
-            # output since pytest defers output until all tests are done) and
-            # move on to the next test. Then the processes are out of sync and
-            # hang until CI times out. Failing on the first test exits quicker
-            # than hanging and prints the error.
-            # Reducing the NCCL timeout instead of using --exitfirst fixes the
-            # hanging but still does not print the error, since it kills both
-            # processes before all tests are done.
-            ./tests/run_tests_with_accelerate.py --coverage -m multigpu --junitxml=/tmp/test-reports/junit-process-\$RANK.xml --durations=500 -vv --exitfirst
+
+            # Put error message of known flakes here.
+            FLAKE_ERROR_MESSAGES=(
+              # GH#826
+              "FileNotFoundError: \[Errno 2\] No such file or directory: '/home/circleci/\.cache/huggingface/"
+            )
+            FLAKE_ERROR_REGEX=$(printf "%s\|" "${FLAKE_ERROR_MESSAGES[@]}")  # Join array elements with "\|"
+            FLAKE_ERROR_REGEX=${FLAKE_ERROR_REGEX%\\|}  # Remove the trailing "\|"
+            FLAKE_ERROR_REGEX="\($FLAKE_ERROR_REGEX\)"
+
+            CYAN="\033[0;36m"
+            RED="\033[0;31m"
+            NO_COLOR="\033[0m"
+            MAX_RETRIES=3
+            for ((i = 0; i < MAX_RETRIES; i++)); do
+              echo -e "${CYAN}----- Attempt $((i + 1)) -----${NO_COLOR}"
+
+              LATEST_EXIT_CODE=0
+              # --exitfirst: Although we'd prefer to see all test results,
+              # sometimes only one process will fail a test (without printing
+              # any output since pytest defers output until all tests are done)
+              # and move on to the next test. Then the processes are out of sync
+              # and hang until CI times out. Failing on the first test exits
+              # quicker than hanging and prints the error.
+              # Reducing the NCCL timeout instead of using --exitfirst fixes the
+              # hanging but still does not print the error, since it kills both
+              # processes before all tests are done.
+              # || LATEST_EXIT_CODE=$?: Gets exit code upon failure but also
+              # makes the overall exit code 0, which we want because otherwise
+              # CI will immediately fail this step due to running with bash -e,
+              # skipping our flake retry logic.
+              ./tests/run_tests_with_accelerate.py --coverage -m multigpu --junitxml=/tmp/test-reports/junit-process-\$RANK.xml --durations=500 -vv --exitfirst || LATEST_EXIT_CODE=$?
+
+              if [ "$LATEST_EXIT_CODE" -eq 0 ]; then
+                exit 0
+              elif grep --quiet "$FLAKE_ERROR_REGEX" /tmp/accelerate_tests_output/* ; then
+                echo -e "${RED}Flaked with exit code $LATEST_EXIT_CODE${NO_COLOR}\n\n"
+              else
+                exit "$LATEST_EXIT_CODE"
+              fi
+            done
+            echo "All retry attempts exhausted. Exiting with last exit code"
+            exit "$LATEST_EXIT_CODE"
           environment:
             WANDB_MODE: offline
       - codecov/upload
